Legacy-Releases/v7.0 - MVC Edition/Original/Eisk.MVC/Controllers/SecurityDemoController.cs
/****************** Copyright Notice *****************
 
This code is licensed under Microsoft Public License (Ms-PL). 
You are free to use, modify and distribute any portion of this code. 
The only requirement to do that, you need to keep the developer name, as provided below to recognize and encourage original work:

=======================================================
   
Architecture Designed and Implemented By:
Mohammad Ashraful Alam
Microsoft Most Valuable Professional, ASP.NET 2007 – 2013
Twitter: http://twitter.com/AshrafulAlam | Blog: http://blog.ashraful.net | Portfolio: http://www.ashraful.net
   
*******************************************************/
namespace Eisk.Controllers
{
    using System.Web.Mvc;
    using System.Web.Security;
    using Eisk.Helpers;
    using Eisk.Models;
    using Eisk.DataAccess;


    public partial class SecurityDemoController : Controller
    {
        public ViewResult Index()
        {
            return View();
        }

        [Authorize]
        public ViewResult Member()
        {
           return View();
        }

        [Authorize(Roles = "Administrator")]
        public ViewResult Admin()
        {
            return View();
        }

        public ViewResult LogOn()
        {
            if (Request.QueryString["ReturnUrl"] != null)
                this.ShowMessage("You need to log-on first with appropriate role to access the page you requested.", MessageType.Error, false);
            return View();
        }

        [HttpPost]
        public ActionResult LogOn(FormCollection fc)
        {
            UserInfo user = UserDataAccess.Validate(fc["userName"], fc["password"]);

            if (user != null)//if the log-in is successful
            {
                FormsAuthentication.RedirectFromLoginPage(user.UserName, fc["checkboxRemember"] == "on");

                if (Request.QueryString["ReturnUrl"] != null)
                    Response.Redirect(System.Web.HttpContext.Current.Request.QueryString["ReturnUrl"].ToString());
                else
                {
                    if (user.UserRole == UserRole.Administrator.ToString())
                        return RedirectToAction("Admin");
                    else
                        return RedirectToAction("Member");
                }
            }
            else
                this.ShowMessage("Invalid user name or password", MessageType.Error, false);

            return View();

        }

        public ViewResult LogOff()
        {
            FormsAuthentication.SignOut();
            System.Web.HttpContext.Current.User = null;
            this.ShowMessage("You have been signed out successfully", MessageType.Notice, false);
            return View("Index");
        }

        public JsonResult GetAllUsers()
        {
            System.Threading.Thread.Sleep(2000);
            return new JsonResult
            {
                Data = UserDataAccess.GetAll(),
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }
    }
}

#region Demo Data


namespace Eisk.Models
{
    public class UserInfo
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string UserRole { get; set; }
    }
}

namespace Eisk.DataAccess
{
    using System.Collections.Generic;
    using Eisk.Models;
    using System.Linq;

    public static class UserDataAccess
    {
        public static IEnumerable<UserInfo> GetAll()
        {
            return UserInMemoryDataSource.ToList();
        }

        public static UserInfo GetByUserName(string userName)
        {
            return UserInMemoryDataSource.FirstOrDefault(u => u.UserName == userName);
        }

        public static UserInfo Validate(string userName, string password)
        {
            return UserInMemoryDataSource.FirstOrDefault(u => u.UserName == userName && u.Password == password);
        }

        static List<UserInfo> _userInMemoryDataSource;
        static List<UserInfo> UserInMemoryDataSource
        {
            get
            {
                if (_userInMemoryDataSource == null)
                {
                    _userInMemoryDataSource = new List<UserInfo>();

                    //add members
                    for (int i = 0; i < 5; i++)
                        _userInMemoryDataSource.Add(
                            new UserInfo
                            {
                                UserName = "member" + (i + 1),
                                Password = "any"
                            });

                    //add administrators
                    for (int i = 0; i < 5; i++)
                        _userInMemoryDataSource.Add(
                            new UserInfo
                            {
                                UserRole = UserRole.Administrator.ToString(),
                                UserName = "admin" + (i + 1),
                                Password = "any"
                            });

                }

                return _userInMemoryDataSource;
            }
        }
    }
}

#endregion

Legacy-Releases/v7.0 - MVC Edition/Original/Eisk.MVC/Views/Shared/_EditorImagePanel.cshtml
@model Eisk.Models.Employee
<!--*******************************************************************************************************************
*                                                                                                                     *
*                                         Script Area                                                                 *
*                                                                                                                     *
********************************************************************************************************************-->
<script type="text/javascript">
/* Upload Image related functions. */
    function uploadFile() {
        var fd = new FormData();
        fd.append("imageUpload", document.getElementById('imageUpload').files[0]);
        var xhr = new XMLHttpRequest();
        xhr.upload.addEventListener("progress", uploadProgress, false);
        xhr.addEventListener("load", uploadComplete, false);
        xhr.addEventListener("error", uploadFailed, false);
        xhr.addEventListener("abort", uploadCanceled, false);
        xhr.open("POST", "@Url.Action("AjaxImageUpload")");
        xhr.responseType = 'blob';
        xhr.send(fd);
        $('#divUploadStatus').show();    
    }

    function uploadProgress(evt) {
        if (evt.lengthComputable) {
            var percentComplete = Math.round(evt.loaded * 100 / evt.total);
            ShowProgress (percentComplete, 100);
        }
        else {
            document.getElementById('progressNumber').innerHTML = 'unable to compute';
        }
    }

    function ShowProgress(currentValue, maxValue)
    {
        document.getElementById('progressNumber').innerHTML = currentValue.toString() + '% uploaded.';
        var progressBar = document.getElementById("progressBar");  
        progressBar.max = maxValue; 
        progressBar.value = currentValue;  
    }

    function uploadComplete(evt) {
        /* This event is raised when the server send back a response */
        if (this.status == 200) {
            ShowProgress(100,100);
            document.getElementById('imageUpload').value = '';
            //loading the respose bytes to image tag
            var blob = this.response;
            var img = document.getElementById('employeeImage');
            img.onload = function(e) {
                window.URL.revokeObjectURL(img.src); // Clean up after yourself.
            };
            img.src = window.URL.createObjectURL(blob);
            $('#divUploadPanel').hide(); 
            $('#btnCancelUpload').show();    
            //document.body.appendChild(img);
        }
    }

    function uploadFailed(evt) {
        alert("There was an error attempting to upload the file.");
    }

    function uploadCanceled(evt) {
        alert("The upload has been canceled by the user or the browser dropped the connection.");
    }
</script>
<script type="text/javascript">
    /* Discard Uploaded Image related functions. */

    $("#btnCancelUpload").live("click", function (e) {
        // Don't post back
        //e.preventDefault();
        $('#divUploadPanel').show();    
        $('#btnCancelUpload').hide();    
        $('#divUploadStatus').hide();       
        ReLoadEmployeeDbImage();
    });

    function ReLoadEmployeeDbImage() 
    {   
        var xhr = new XMLHttpRequest();
        xhr.addEventListener("load", DownloadEmployeeDbImageComplete, false);
        xhr.open("GET", "@Url.Action("DiscardUploadededImage", new { id = Model.Id })");
        xhr.responseType = 'blob';
        xhr.send();

        $('#ajax-loader').show();
    }

    function DownloadEmployeeDbImageComplete(evt) {
        if (this.status == 200) {
            var blob = this.response;
            var img = document.getElementById('employeeImage');
            img.onload = function(e) {
                window.URL.revokeObjectURL(img.src); // Clean up after yourself.
            };
            img.src = window.URL.createObjectURL(blob);
            
        }

        $('#ajax-loader').hide();
    }

</script>
<!-- Picture Area -->
@Html.LabelFor(model => model.Photo): @Html.RequiredSymbolFor(model => model.Photo)<br
    class="clear" />
<a href="@Url.Action("EmployeeImageFile", new { id = Model.Id })" target="_blank">
    <img id="employeeImage" alt="employee image" class="profile-image" src="@Url.Action("EmployeeImageFile", new { id = (Model.Id) })" /><br />
</a>
<label>
    Upload New Image:</label><br />
<div id="divUploadPanel">
    <input type="file" id="imageUpload" name="imageUpload" onchange="uploadFile();" /><br />
    @if (Model.Id != 0 && Model.Photo != null)
    {<input type="checkbox" id="removeImage" name="removeImage" /><text>Remove Image</text>}
</div>
<div id="divUploadStatus" style="display: none">
    <progress id="progressBar">
    </progress>
    <span id="progressNumber" />
</div>
<a href="#" id="btnCancelUpload" style="display: none">Discard upload</a>
<img id="ajax-loader" src="../../Images/loader-life.gif" style="display: none" />
<br class="clear" />
<!-- Picture Area Ends -->

Legacy-Releases/v7.0 - MVC Edition/Original/Eisk.MVC/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>EISK MVC (Mobile) - @ViewBag.Title</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link rel="shortcut icon" href="@Url.Content("~/Images/favicon.ico")" />
    <!-- main CSS -->
    <link href="@Url.Content("~/content/themes/default/reset.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/content/themes/default/960.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/content/themes/default/text.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/content/themes/default/layout.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/content/themes/default/bread-crumb.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/content/themes/default/buttons.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/content/themes/default/forms.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/content/themes/default/grids.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/content/themes/default/overcast/jquery-ui-1.8.18.custom.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/content/themes/default/mvc-default.css")" rel="stylesheet" type="text/css" />
    <!-- mobile related CSS to be placed after main CSS -->
    <link rel="stylesheet" href="@Url.Content("~/content/themes/default/mobile/jquery.mobile/jquery.mobile-1.0.1.min.css")" />
    <link href="@Url.Content("~/content/themes/default/mobile/mobile.css")" rel="stylesheet" type="text/css" />
    <!-- main scripts -->
    <script type="text/javascript" src="@Url.Content("~/scripts/jquery-1.6.4.js")"></script>
    <!-- mobile related scripts to be placed after main scripts -->
    <script type="text/javascript" src="@Url.Content("~/scripts/jquery.mobile-1.0.1.min.js")"></script>
    <script type="text/javascript">
        $(document).bind("mobileinit", function () {
            // As of Beta 2, jQuery Mobile's Ajax navigation does not work in all cases (e.g.,
            // when navigating from a mobile to a non-mobile page), hence disabling it.
            $.mobile.ajaxEnabled = false;
        });
    </script>
</head>
<body>
    <div data-role="page" data-theme="a">
        <div data-role="header">
            @Html.Partial("_ViewSwitcher")
        </div>
        <div data-role="content">
            @Html.RenderMessages()
            @RenderBody()
        </div>
    </div>
</body>
</html>

Legacy-Releases/v7.0 - MVC Edition/Original/Eisk.MVC/Views/Shared/_Layout.cshtml
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <title>EISK MVC - @ViewBag.Title</title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <meta name="description" content="Description of your web page goes here." />
    <meta name="keywords" content="Keywords for you web page go here. Each keyword or group of keyword phrases are separated by a comma. Keep this keyword list short and relevant to the content of this specific page and also relevant to the tile of the specific page" />
    <meta name="viewport" content="width=device-width" />
    <link rel="shortcut icon" href="@Url.Content("~/Images/favicon.ico")" />
    <!-- global CSS -->
    <link href="@Url.Content("~/content/themes/default/reset.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/content/themes/default/960.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/content/themes/default/text.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/content/themes/default/layout.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/content/themes/default/bread-crumb.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/content/themes/default/buttons.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/content/themes/default/forms.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/content/themes/default/grids.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/content/themes/default/overcast/jquery-ui-1.8.18.custom.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/content/themes/default/mvc-default.css")" rel="stylesheet" type="text/css" />
    <!-- global scripts -->
    <script type='text/javascript' src="@Url.Content("~/scripts/jquery-1.6.4.js")"></script>
    <script type='text/javascript' src="@Url.Content("~/scripts/eisk-menu.js")"></script>
    <script type='text/javascript' src="@Url.Content("~/scripts/eisk-ajax-loader.js")"></script>
</head>
<body>
    @Html.RenderMessages()
    <div class="header clearfix">
        <div class="container_16">
            <a href="@Url.Content("~")" class="branding grid_3 alpha"></a>
            <div class="top-nav grid_8" id="ParentMenu">
                <a href="@Url.Content("~/")">EISK</a> <a href="@Url.Content("~/Employees/")">Employees</a>
                <a href="@Url.Content("~/SecurityDemo/")">Security Samples</a>
            </div>
            <div class="grid_5 utility-menu omega">
                @if (Request.IsAuthenticated)
                {
                    <text><strong>Welcome @User.Identity.Name</strong> | @Html.ActionLink("Log Off", "LogOff", "SecurityDemo")
                    </text> }
                else
                {
                    @:@Html.ActionLink("Log on", "LogOn", "SecurityDemo")

                                                                                                                                                                                                                                                                                                              
                }
                @if (HttpContext.Current.IsDebuggingEnabled)
                {
                    <text> | </text> <a href="@Url.Content("~/Home/ResetData")">Reset data</a>  }
            </div>
        </div>
    </div>
    <div class="content-top clearfix">
        <div class="container_16" id="ChildMenuContainer">
            <div class="sub-nav">
                <a href="@Url.Content("~/")">EISK Home</a> | <a href="@Url.Content("~/Home/About/")">About</a>
            </div>
            <div class="sub-nav">
                <a href="@Url.Content("~/Employees/Index")">Employee Listing</a> | <a href="@Url.Content("~/Employees/Create")">Create Employee</a> | <a href="@Url.Content("~/Employees/Edit/1")">Edit Employee</a>
                | <a href="@Url.Content("~/Employees/Details/1")">View Employee</a>
            </div>
            <div class="sub-nav">
                <a href="@Url.Content("~/SecurityDemo/Member")">Member Area</a> | <a href="@Url.Content("~/SecurityDemo/Admin")">Admin Area</a>
            </div>
        </div>
    </div>
    <div class="content-main">
        <div class="container_16">
            <img id="loading-image" src="@Url.Content("~/Images/loader-life.gif")" style="display: none" />
            @Html.Partial("_ViewSwitcher")
            @RenderBody()
        </div>
    </div>
    <div class="footer">
        <div class="container_16">
            <div class="grid_10 alpha">
                Employee Info Starter Kit is a web application that illustrate a wide range of architectural
                guidelines and samples to address different types of real world challenges faced
                by web application developers.<br />
            </div>
            <div class="grid_6 omega">
                Copyright &copy; @System.DateTime.Now.Year <a href="http://www.facebook.com/ashraful.alam"
                    target="_blank">Ashraful Alam</a>
                <br />
                Project Site: <a href="https://github.com/EISK" target="_blank">EISK</a>
            </div>
        </div>
    </div>
</body>
</html>

Legacy-Releases/v7.0 - MVC Edition/Original/Eisk.MVC/Views/Shared/_ViewSwitcher.cshtml
@* TO DO: Fix: Theme Switcher Doesn't work for iPhone (i.e. special browser). *@

@if (Request.Browser.IsMobileDevice && Request.HttpMethod == "GET")
{
    <div class="view-switcher ui-bar-a">
        @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
        {
            @: Displaying mobile view
            @Html.ActionLink("Desktop view", "SwitchView", "Home", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        } 
        else 
        {
            @: Displaying desktop view
            @Html.ActionLink("Mobile view", "SwitchView", "Home", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
    </div>
}